version: '3.7'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    networks:
      - reverse-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  champions-nginx:
    image: nginx:1.19-alpine
    working_dir: /app
    volumes:
      - ../public:/app
      - ../docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - champions-php-fpm
    networks:
      reverse-proxy:
      champions-api:
      main:
        aliases:
          - ${DOMAIN}
    environment:
      - VIRTUAL_HOST=${DOMAIN}

  champions-php-fpm:
    dns:
      - 8.8.8.8
    build:
      context: ../
      dockerfile: docker/php/Dockerfile
      args:
        - UID=${UID}
        - GID=${GID}
    user: ${UID}:${GID}
    volumes:
      - ../:/app
    restart: on-failure
    working_dir: /app
    env_file:
      - .env
    networks:
      - champions-api

  champions-mysql:
    image: mysql:8
    restart: on-failure
    user: ${UID}:${GID}
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - champions-api-mysql-data:/var/lib/mysql
    ports:
      - 3351:3306
    networks:
      - champions-api
      - main

volumes:
  champions-api-mysql-data:
    driver: local

networks:
  champions-api:
  reverse-proxy:
    external: true
  main:
    external:
      name: champions_default